### ISSUE TITLE
Roadmap: Apocalint-SYS pylint-odoo -> oca-odoo-pre-commit-hooks

### ISSUE THREAD

**Issue by moylop260** [OCA/odoo-pre-commit-hooks#30]
- [ ] Add configuration file support to disable checks by file similar a prettier or using the .pre-commit-conf.yaml is enough?
- [ ] Add parameter option to configure lints by range of odoo version or using the .pre-commit-conf.yaml is enough (since it is differente by each odoo version)?
- [ ] Add `--list-msgs` similar to pylint in order to show all the current available checks
- [ ] Add documentation build
- [ ] Changelog: Add date (similar to isort) & add github URL to PRs
- [ ] Update requirements.txt packages to latest or closes to odoo v16.0 versions
- [ ] Create a duplicated xmlid based on csv + xml in test_repo
- [ ] Add https://github.com/PyCQA/doc8 instead of rst-lint in documentation in order to use it instead of develop it
- [ ] Check if there is a regression issue with migrations folder considered as an extra odoo package like pylint-odoo old issue
